set nocompatible

syntax on
color verde

set background=dark
set tabstop=3
set softtabstop=3
set shiftwidth=3
set expandtab
set incsearch
set viminfo=""
set ruler
set noswapfile
set encoding=utf-8
set fileencoding=utf-8
set autoindent
set smartindent
" set laststatus=2
set hidden
set wildmenu

set tags=tags;$HOME

autocmd FileType make set noexpandtab

let g:lsc_auto_map = v:true

let g:lsc_server_commands = {
 \  'c': {
 \    'command': 'clangd',
 \    'log_level': -1,
 \    'suppress_stderr': v:true,
 \  },
 \ }

