set nocompatible

syntax on
color verde

set background=dark
set tabstop=8
set softtabstop=8
set shiftwidth=8
" set expandtab
set incsearch
set viminfo=""
set ruler
set noswapfile
set encoding=utf-8
set fileencoding=utf-8
set autoindent
set smartindent
set laststatus=2
set hidden
set wildmenu

set tags=tags;$HOME

autocmd FileType make set noexpandtab
